<a href="https://colab.research.google.com/github/anavlajovic/ml-lab/blob/main/Mreza%20BEZ%20pytorcha.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from time import sleep

d = np.array(pd.read_csv('mnist_train.csv'))

In [2]:

m, n = d.shape
np.random.shuffle(d) # shuffle before splitting into dev and training sets

train = d[1000:m].T
Y = train[0]
X = train[1:n]
X = X / 255
_,mt = X.shape

def init():
    global W1, b1, W2, b2
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5

def sm(Z): # softmax
    return np.exp(Z) / sum(np.exp(Z))

def forward():
    global Z1, A1, Z2, A2
    Z1 = W1.dot(X) + b1
    A1 = np.maximum(Z1, 0)  # Relu
    Z2 = W2.dot(A1) + b2
    A2 = sm(Z2)

def oh(): #onehot
    ohy = np.zeros((Y.size, Y.max() + 1))
    ohy[np.arange(Y.size), Y] = 1
    return ohy.T

def back():
    global dW1, db1, dW2, db2
    dZ2 = A2 - oh()
    dW2 = dZ2.dot(A1.T) / m
    db2 = np.sum(dZ2) / m
    dZ1 = W2.T.dot(dZ2) * (Z1>0)
    dW1 = dZ1.dot(X.T) / m
    db1 = np.sum(dZ1) / m

def update(lr):
    global W1, b1, W2, b2
    W1 = W1 - lr * dW1
    b1 = b1 - lr * db1
    W2 = W2 - lr * dW2
    b2 = b2 - lr * db2

def accuracy(pred):
    print(pred, Y)
    return np.sum(pred == Y) / Y.size

def gd(lr, iters):
    init()
    for i in range(iters):
        forward()
        back()
        update(lr)
        if i % 25 == 0:
            print(i, accuracy(np.argmax(A2, 0)))

In [ ]:
gd(0.10, 500)

[5 8 8 ... 5 1 5] [6 6 2 ... 0 2 1]
0 0.12442760145270804
[0 8 6 ... 6 2 1] [6 6 2 ... 0 2 1]
25 0.2965945576082952
[3 8 6 ... 5 2 1] [6 6 2 ... 0 2 1]
50 0.4581293752302753
[9 8 6 ... 5 2 1] [6 6 2 ... 0 2 1]
75 0.5549765777146165
[9 8 0 ... 0 2 1] [6 6 2 ... 0 2 1]
100 0.6247170903731776
[9 8 0 ... 0 2 1] [6 6 2 ... 0 2 1]
125 0.6747723564398126
[9 8 0 ... 0 2 1] [6 6 2 ... 0 2 1]
150 0.708668877309332
[4 6 0 ... 0 2 1] [6 6 2 ... 0 2 1]
175 0.7334596557713564
[4 6 0 ... 0 2 1] [6 6 2 ... 0 2 1]
200 0.7517764092846992
[4 6 2 ... 0 2 1] [6 6 2 ... 0 2 1]
225 0.7667245644507605
[4 6 2 ... 0 2 1] [6 6 2 ... 0 2 1]
250 0.7793041739038897
[4 6 2 ... 0 2 1] [6 6 2 ... 0 2 1]
275 0.7900942154850256
